#Definindo o nome do Worflow
name: Meu Primeiro Workflow no GitHub Actions
on:
  push:
    branches: [ main, developer]
#Definindo os jobs que o Workflow executará
jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: ubuntu-hosted
    steps:
      - name: Step01 - Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: 'santosandre'
          password: ${{secrets.DOCKERHUB_SENHA}}
